/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/* automatically generated by rust-bindgen 0.71.1 */

#![allow(dead_code)]

use mlir_sys::*;

unsafe extern "C" {
    #[doc = " Add all the dialects provided by cuda_tile to the registry."]
    pub fn mlirCudaTileRegisterAllDialects(registry: MlirDialectRegistry);
}
unsafe extern "C" {
    #[doc = " Add all the passes provided by cuda_tile."]
    pub fn mlirCudaTileRegisterAllPasses();
}
unsafe extern "C" {
    pub fn mlirGetDialectHandle__cuda_tile__() -> MlirDialectHandle;
}
unsafe extern "C" {
    #[doc = " Returns true if the given type is a cuda_tile PointerType."]
    pub fn mlirCudaTileTypeIsAPointerType(type_: MlirType) -> bool;
}
unsafe extern "C" {
    #[doc = " Returns the TypeID for cuda_tile PointerType."]
    pub fn mlirCudaTilePointerTypeGetTypeID() -> MlirTypeID;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile PointerType with the given pointee type in the given\n context."]
    pub fn mlirCudaTilePointerTypeGet(ctx: MlirContext, pointeeType: MlirType) -> MlirType;
}
unsafe extern "C" {
    #[doc = " Returns the pointee type of the given cuda_tile PointerType."]
    pub fn mlirCudaTilePointerTypeGetPointeeType(type_: MlirType) -> MlirType;
}
unsafe extern "C" {
    #[doc = " Returns true if the given type is a cuda_tile TileType."]
    pub fn mlirCudaTileTypeIsATileType(type_: MlirType) -> bool;
}
unsafe extern "C" {
    #[doc = " Returns the TypeID for cuda_tile TileType."]
    pub fn mlirCudaTileTileTypeGetTypeID() -> MlirTypeID;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile TileType with the given shape and element type."]
    pub fn mlirCudaTileTileTypeGet(
        ctx: MlirContext,
        rank: isize,
        shape: *const i64,
        elementType: MlirType,
    ) -> MlirType;
}
unsafe extern "C" {
    #[doc = " Returns the element type of the given cuda_tile TileType."]
    pub fn mlirCudaTileTileTypeGetElementType(type_: MlirType) -> MlirType;
}
unsafe extern "C" {
    #[doc = " Returns the rank of the given cuda_tile TileType."]
    pub fn mlirCudaTileTileTypeGetRank(type_: MlirType) -> isize;
}
unsafe extern "C" {
    #[doc = " Returns the shape of the given cuda_tile TileType at the given index."]
    pub fn mlirCudaTileTileTypeGetDimSize(type_: MlirType, pos: isize) -> i64;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile TileType with the given shape and element type,\n performing verification. Returns a null type if verification fails."]
    pub fn mlirCudaTileTileTypeGetChecked(
        ctx: MlirContext,
        rank: isize,
        shape: *const i64,
        elementType: MlirType,
    ) -> MlirType;
}
unsafe extern "C" {
    #[doc = " Returns true if the given type is a cuda_tile TokenType."]
    pub fn mlirCudaTileTypeIsATokenType(type_: MlirType) -> bool;
}
unsafe extern "C" {
    #[doc = " Returns the TypeID for cuda_tile TokenType."]
    pub fn mlirCudaTileTokenTypeGetTypeID() -> MlirTypeID;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile TokenType."]
    pub fn mlirCudaTileTokenTypeGet(ctx: MlirContext) -> MlirType;
}
unsafe extern "C" {
    #[doc = " Returns true if the given type is a cuda_tile TensorViewType."]
    pub fn mlirCudaTileTypeIsATensorViewType(type_: MlirType) -> bool;
}
unsafe extern "C" {
    #[doc = " Returns the TypeID for cuda_tile TensorViewType."]
    pub fn mlirCudaTileTensorViewTypeGetTypeID() -> MlirTypeID;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile TensorViewType with the given element type, shape, and\n strides."]
    pub fn mlirCudaTileTensorViewTypeGet(
        ctx: MlirContext,
        elementType: MlirType,
        shapeRank: isize,
        shape: *const i64,
        strideRank: isize,
        strides: *const i64,
    ) -> MlirType;
}
unsafe extern "C" {
    #[doc = " Returns the element type of the given cuda_tile TensorViewType."]
    pub fn mlirCudaTileTensorViewTypeGetElementType(type_: MlirType) -> MlirType;
}
unsafe extern "C" {
    #[doc = " Returns the rank of the given cuda_tile TensorViewType."]
    pub fn mlirCudaTileTensorViewTypeGetRank(type_: MlirType) -> isize;
}
unsafe extern "C" {
    #[doc = " Returns the shape of the given cuda_tile TensorViewType at the given index."]
    pub fn mlirCudaTileTensorViewTypeGetDimSize(type_: MlirType, pos: isize) -> i64;
}
unsafe extern "C" {
    #[doc = " Returns the stride of the given cuda_tile TensorViewType at the given index."]
    pub fn mlirCudaTileTensorViewTypeGetStride(type_: MlirType, pos: isize) -> i64;
}
unsafe extern "C" {
    #[doc = " Returns the dynamic dimension constant for TensorViewType."]
    pub fn mlirCudaTileTensorViewTypeGetDynamicSize() -> i64;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile TensorViewType with the given element type, shape, and\n strides, performing verification. Returns a null type if verification fails."]
    pub fn mlirCudaTileTensorViewTypeGetChecked(
        ctx: MlirContext,
        elementType: MlirType,
        shapeRank: isize,
        shape: *const i64,
        strideRank: isize,
        strides: *const i64,
    ) -> MlirType;
}
unsafe extern "C" {
    #[doc = " Returns true if the given type is a cuda_tile PartitionViewType."]
    pub fn mlirCudaTileTypeIsAPartitionViewType(type_: MlirType) -> bool;
}
unsafe extern "C" {
    #[doc = " Returns the TypeID for cuda_tile PartitionViewType."]
    pub fn mlirCudaTilePartitionViewTypeGetTypeID() -> MlirTypeID;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile PartitionViewType with the given tile shape, tensor\n view, dim map, and optional padding value."]
    pub fn mlirCudaTilePartitionViewTypeGet(
        ctx: MlirContext,
        tileShapeAttr: MlirAttribute,
        tensorViewType: MlirType,
        dimMapRank: isize,
        dimMap: *const i32,
        paddingValue: MlirAttribute,
    ) -> MlirType;
}
unsafe extern "C" {
    #[doc = " Returns the tile shape attribute of the given cuda_tile PartitionViewType."]
    pub fn mlirCudaTilePartitionViewTypeGetTileShape(type_: MlirType) -> MlirAttribute;
}
unsafe extern "C" {
    #[doc = " Returns the tensor view type of the given cuda_tile PartitionViewType."]
    pub fn mlirCudaTilePartitionViewTypeGetTensorView(type_: MlirType) -> MlirType;
}
unsafe extern "C" {
    #[doc = " Returns the rank of the dim map of the given cuda_tile PartitionViewType."]
    pub fn mlirCudaTilePartitionViewTypeGetDimMapRank(type_: MlirType) -> isize;
}
unsafe extern "C" {
    #[doc = " Returns the dim map element at the given index of the given cuda_tile\n PartitionViewType."]
    pub fn mlirCudaTilePartitionViewTypeGetDimMapElement(type_: MlirType, pos: isize) -> i32;
}
unsafe extern "C" {
    #[doc = " Returns the padding value attribute of the given cuda_tile PartitionViewType\n (may be null)."]
    pub fn mlirCudaTilePartitionViewTypeGetPaddingValue(type_: MlirType) -> MlirAttribute;
}
unsafe extern "C" {
    #[doc = " Returns the view tile type of the given cuda_tile PartitionViewType."]
    pub fn mlirCudaTilePartitionViewTypeGetViewTileType(type_: MlirType) -> MlirType;
}
unsafe extern "C" {
    #[doc = " Returns the view index rank of the given cuda_tile PartitionViewType."]
    pub fn mlirCudaTilePartitionViewTypeGetViewIndexRank(type_: MlirType) -> isize;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile PartitionViewType with the given tile shape, tensor\n view, dim map, and padding value, performing verification. Returns a null\n type if verification fails."]
    pub fn mlirCudaTilePartitionViewTypeGetChecked(
        ctx: MlirContext,
        tileShapeAttr: MlirAttribute,
        tensorViewType: MlirType,
        dimMapRank: isize,
        dimMap: *const i32,
        paddingValue: MlirAttribute,
    ) -> MlirType;
}
unsafe extern "C" {
    #[doc = " Returns true if the given attribute is a cuda_tile RoundingModeAttr."]
    pub fn mlirCudaTileAttributeIsARoundingModeAttr(attr: MlirAttribute) -> bool;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile RoundingModeAttr with the given rounding mode string."]
    pub fn mlirCudaTileRoundingModeAttrGet(ctx: MlirContext, value: MlirStringRef)
        -> MlirAttribute;
}
unsafe extern "C" {
    #[doc = " Returns the rounding mode string of the given cuda_tile RoundingModeAttr."]
    pub fn mlirCudaTileRoundingModeAttrGetValue(attr: MlirAttribute) -> MlirStringRef;
}
unsafe extern "C" {
    #[doc = " Returns true if the given attribute is a cuda_tile ComparisonOrderingAttr."]
    pub fn mlirCudaTileAttributeIsAComparisonOrderingAttr(attr: MlirAttribute) -> bool;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile ComparisonOrderingAttr with the given ordering string."]
    pub fn mlirCudaTileComparisonOrderingAttrGet(
        ctx: MlirContext,
        value: MlirStringRef,
    ) -> MlirAttribute;
}
unsafe extern "C" {
    #[doc = " Returns the comparison ordering string of the given cuda_tile\n ComparisonOrderingAttr."]
    pub fn mlirCudaTileComparisonOrderingAttrGetValue(attr: MlirAttribute) -> MlirStringRef;
}
unsafe extern "C" {
    #[doc = " Returns true if the given attribute is a cuda_tile ComparisonPredicateAttr."]
    pub fn mlirCudaTileAttributeIsAComparisonPredicateAttr(attr: MlirAttribute) -> bool;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile ComparisonPredicateAttr with the given predicate string."]
    pub fn mlirCudaTileComparisonPredicateAttrGet(
        ctx: MlirContext,
        value: MlirStringRef,
    ) -> MlirAttribute;
}
unsafe extern "C" {
    #[doc = " Returns the comparison predicate string of the given cuda_tile\n ComparisonPredicateAttr."]
    pub fn mlirCudaTileComparisonPredicateAttrGetValue(attr: MlirAttribute) -> MlirStringRef;
}
unsafe extern "C" {
    #[doc = " Creates a DenseI32ArrayAttr with the given values."]
    pub fn mlirCudaTileDenseI32ArrayAttrGet(
        ctx: MlirContext,
        numElements: isize,
        values: *const i32,
    ) -> MlirAttribute;
}
unsafe extern "C" {
    #[doc = " Returns the number of elements in a DenseI32ArrayAttr."]
    pub fn mlirCudaTileDenseI32ArrayAttrGetNumElements(attr: MlirAttribute) -> isize;
}
unsafe extern "C" {
    #[doc = " Returns the element at the given index in a DenseI32ArrayAttr."]
    pub fn mlirCudaTileDenseI32ArrayAttrGetElement(attr: MlirAttribute, pos: isize) -> i32;
}
unsafe extern "C" {
    #[doc = " Returns true if the given attribute is a cuda_tile\n MemoryOrderingSemanticsAttr."]
    pub fn mlirCudaTileAttributeIsAMemoryOrderingSemanticsAttr(attr: MlirAttribute) -> bool;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile MemoryOrderingSemanticsAttr with the given semantics\n string."]
    pub fn mlirCudaTileMemoryOrderingSemanticsAttrGet(
        ctx: MlirContext,
        value: MlirStringRef,
    ) -> MlirAttribute;
}
unsafe extern "C" {
    #[doc = " Returns the memory ordering semantics string of the given cuda_tile\n MemoryOrderingSemanticsAttr."]
    pub fn mlirCudaTileMemoryOrderingSemanticsAttrGetValue(attr: MlirAttribute) -> MlirStringRef;
}
unsafe extern "C" {
    #[doc = " Returns true if the given attribute is a cuda_tile MemoryScopeAttr."]
    pub fn mlirCudaTileAttributeIsAMemoryScopeAttr(attr: MlirAttribute) -> bool;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile MemoryScopeAttr with the given scope string."]
    pub fn mlirCudaTileMemoryScopeAttrGet(ctx: MlirContext, value: MlirStringRef) -> MlirAttribute;
}
unsafe extern "C" {
    #[doc = " Returns the memory scope string of the given cuda_tile MemoryScopeAttr."]
    pub fn mlirCudaTileMemoryScopeAttrGetValue(attr: MlirAttribute) -> MlirStringRef;
}
unsafe extern "C" {
    #[doc = " Returns true if the given attribute is a cuda_tile PaddingValueAttr."]
    pub fn mlirCudaTileAttributeIsAPaddingValueAttr(attr: MlirAttribute) -> bool;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile PaddingValueAttr with the given padding value string."]
    pub fn mlirCudaTilePaddingValueAttrGet(ctx: MlirContext, value: MlirStringRef)
        -> MlirAttribute;
}
unsafe extern "C" {
    #[doc = " Returns the padding value string of the given cuda_tile PaddingValueAttr."]
    pub fn mlirCudaTilePaddingValueAttrGetValue(attr: MlirAttribute) -> MlirStringRef;
}
unsafe extern "C" {
    #[doc = " Returns true if the given attribute is a cuda_tile AtomicRMWModeAttr."]
    pub fn mlirCudaTileAttributeIsAAtomicRMWModeAttr(attr: MlirAttribute) -> bool;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile AtomicRMWModeAttr with the given mode string."]
    pub fn mlirCudaTileAtomicRMWModeAttrGet(
        ctx: MlirContext,
        value: MlirStringRef,
    ) -> MlirAttribute;
}
unsafe extern "C" {
    #[doc = " Returns the atomic RMW mode string of the given cuda_tile AtomicRMWModeAttr."]
    pub fn mlirCudaTileAtomicRMWModeAttrGetValue(attr: MlirAttribute) -> MlirStringRef;
}
unsafe extern "C" {
    #[doc = " Returns true if the given attribute is a cuda_tile IntegerOverflowAttr."]
    pub fn mlirCudaTileAttributeIsAIntegerOverflowAttr(attr: MlirAttribute) -> bool;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile IntegerOverflowAttr with the given overflow string."]
    pub fn mlirCudaTileIntegerOverflowAttrGet(
        ctx: MlirContext,
        value: MlirStringRef,
    ) -> MlirAttribute;
}
unsafe extern "C" {
    #[doc = " Returns the integer overflow string of the given cuda_tile\n IntegerOverflowAttr."]
    pub fn mlirCudaTileIntegerOverflowAttrGetValue(attr: MlirAttribute) -> MlirStringRef;
}
unsafe extern "C" {
    #[doc = " Returns true if the given attribute is a cuda_tile SignednessAttr."]
    pub fn mlirCudaTileAttributeIsASignednessAttr(attr: MlirAttribute) -> bool;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile SignednessAttr with the given signedness string."]
    pub fn mlirCudaTileSignednessAttrGet(ctx: MlirContext, value: MlirStringRef) -> MlirAttribute;
}
unsafe extern "C" {
    #[doc = " Returns the signedness string of the given cuda_tile SignednessAttr."]
    pub fn mlirCudaTileSignednessAttrGetValue(attr: MlirAttribute) -> MlirStringRef;
}
unsafe extern "C" {
    #[doc = " Returns true if the given attribute is a cuda_tile OptimizationHintsAttr."]
    pub fn mlirCudaTileAttributeIsAOptimizationHintsAttr(attr: MlirAttribute) -> bool;
}
unsafe extern "C" {
    #[doc = " Returns an empty cuda_tile OptimizationHintsAttr."]
    pub fn mlirCudaTileOptimizationHintsAttrGetEmpty(ctx: MlirContext) -> MlirAttribute;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile OptimizationHintsAttr with EntryOp hints for the given\n architecture. Pass 0 for unused parameters."]
    pub fn mlirCudaTileOptimizationHintsAttrGetEntryOpHint(
        ctx: MlirContext,
        arch: MlirStringRef,
        numCta: i32,
        occupancy: i32,
    ) -> MlirAttribute;
}
unsafe extern "C" {
    #[doc = " Returns a cuda_tile OptimizationHintsAttr with LoadStore hints for the given\n architecture. Pass 0 for latency and false for allowTma if unused."]
    pub fn mlirCudaTileOptimizationHintsAttrGetLoadStoreOpHint(
        ctx: MlirContext,
        arch: MlirStringRef,
        allowTma: i8,
        latency: i32,
    ) -> MlirAttribute;
}
unsafe extern "C" {
    #[doc = " Returns true if the operation is a cuda_tile ModuleOp."]
    pub fn mlirCudaTileOperationIsAModuleOp(op: MlirOperation) -> bool;
}
unsafe extern "C" {
    #[doc = " Returns true if the operation is a standard MLIR ModuleOp."]
    pub fn mlirOperationIsAModuleOp(op: MlirOperation) -> bool;
}
unsafe extern "C" {
    #[doc = " Applies TileIR optimizations to a cuda_tile module operation.\n Returns true on success, false on failure.\n Note: This is a high-level function that would need extensive CAPI\n infrastructure."]
    pub fn mlirCudaTileApplyOptimizations(
        moduleOp: MlirOperation,
        loopSplitThreshold: i32,
        enableCSE: bool,
        canonicalizeBefore: bool,
        canonicalizeAfter: bool,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " Writes a cuda_tile module to bytecode format using a file descriptor.\n Returns true on success, false on failure.\n Note: This function would need CAPI for bytecode writing and operation\n casting."]
    pub fn mlirCudaTileWriteBytecode(
        moduleOp: MlirOperation,
        fileDescriptor: ::std::os::raw::c_int,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " Writes a cuda_tile module to bytecode format to a memory buffer.\n Returns an MlirStringRef containing the bytecode data (with length).\n Returns empty string ref on failure.\n Caller must free the buffer using mlirCudaTileFreeBuffer."]
    pub fn mlirCudaTileWriteBytecodeToBuffer(moduleOp: MlirOperation) -> MlirStringRef;
}
unsafe extern "C" {
    #[doc = " Frees a buffer returned by mlirCudaTileWriteBytecodeToBuffer."]
    pub fn mlirCudaTileFreeBuffer(buffer: MlirStringRef);
}
unsafe extern "C" {
    #[doc = " Creates an integer type with the given width."]
    pub fn mlirCudaTileIntegerTypeGet(ctx: MlirContext, width: ::std::os::raw::c_uint) -> MlirType;
}
unsafe extern "C" {
    #[doc = " Creates an integer attribute with the given type and value."]
    pub fn mlirCudaTileIntegerAttrGet(type_: MlirType, value: i64) -> MlirAttribute;
}
unsafe extern "C" {
    #[doc = " Sets a discardable attribute on an operation by name."]
    pub fn mlirCudaTileOperationSetDiscardableAttributeByName(
        op: MlirOperation,
        name: MlirStringRef,
        attr: MlirAttribute,
    );
}
unsafe extern "C" {
    #[doc = " Registers all CudaTile passes with the global pass registry."]
    pub fn mlirCudaTileRegisterPasses();
}
unsafe extern "C" {
    #[doc = " Registers individual CudaTile passes with the global pass registry."]
    pub fn mlirCudaTileRegisterSynthesizeDebugInfoScopesPass();
}
unsafe extern "C" {
    pub fn mlirCudaTileRegisterFuseFMAPass();
}
unsafe extern "C" {
    pub fn mlirCudaTileRegisterLoopSplitPass();
}
unsafe extern "C" {
    #[doc = " Registers standard MLIR passes with the global pass registry."]
    pub fn mlirCudaTileRegisterCanonicalizerPass();
}
unsafe extern "C" {
    pub fn mlirCudaTileRegisterCSEPass();
}
